### ISSUE TITLE
osx M1 not work

### ISSUE THREAD

**Issue by zyfyy** [g-plane/pnpm-shell-completion#13]
system: OSX M1

` _pnpm:17: bad CPU type in executable: /Users/qi/.zi/plugins/g-plane---pnpm-shell-completion/pnpm-shell-completion`

guess rs not build for M1 cpu

**Comment by g-plane** [comment]
You downloaded wrong files.

**Comment by zyfyy** [comment]
> You downloaded wrong files.

i use zinit so it should install through `zplug.zsh` which should download the right file.

是不是产出本身有点问题？

**Comment by g-plane** [comment]
If you doubt, you can try installing manually without zinit or zplug.

**Comment by g-plane** [comment]
Close due to no responses.
