### ISSUE TITLE
need detailed instructions for how to install with oh-my-zsh manual

### ISSUE THREAD

**Issue by jcodog** [g-plane/pnpm-shell-completion#23]
I downloaded the binaries, added them to the custom/plugins folder and cloned the repo there as well. It still doesnt work?

**Comment by g-plane** [comment]
Please provide detailed environment information and steps about how you install.

**Comment by jcodog** [comment]
windows 64 bit

cloned the entire git repo into the root folder (~)

downloaded the binaries and extracted them into pnpm-shell-completion folder that I had to create in the repo folder

ran the install command as instructed in the guide

output
`./install.zsh $ZSH_CUSTOM/plugins
+ '[' -z /c/Users/bling/.oh-my-zsh/custom/plugins ']'
+ '[' '!' -d /c/Users/bling/.oh-my-zsh/custom/plugins/pnpm-shell-completion ']'
+ cp ./pnpm-shell-completion.plugin.zsh /c/Users/bling/.oh-my-zsh/custom/plugins/pnpm-shell-completion
+ cp ./pnpm-shell-completion /c/Users/bling/.oh-my-zsh/custom/plugins/pnpm-shell-completion
cp: -r not specified; omitting directory './pnpm-shell-completion'`

**Comment by g-plane** [comment]
Only PowerShell Core is supported on Windows.

**Comment by jcodog** [comment]
I use gitbash and have used zsh through that

I also have ubuntu running on this through wsl

**Comment by g-plane** [comment]
Git Bash isn't supported. WSL is using Bash by default.

**Comment by jcodog** [comment]
Wouldnt GitBash work as it runs all zsh plugins correctly?
I can install and use other ZSH features seamlessly, is there no way to make this work with this plugin?

**Comment by g-plane** [comment]
For Windows users:

- Use PowerShell Core
- Use zsh/fish inside WSL

**Comment by jcodog** [comment]
Oh how do I install it for wsl?

**Comment by g-plane** [comment]
Once you have WSL, just follow the guide as being in Linux.

**Comment by jcodog** [comment]
Installed with bunx but it does't show the completions? Do I need any other plugins enabled?

**Comment by g-plane** [comment]
That script isn't maintained by me. You should ask help to its author.
