### ISSUE TITLE
How to install with Zim?

### ISSUE THREAD

**Issue by jclaveau** [g-plane/pnpm-shell-completion#25]
Is there a recommended way to install it with Zim? https://github.com/zimfw/zimfw

**Comment by g-plane** [comment]
Try:

```
zmodule g-plane/pnpm-shell-completion
```

**Comment by jclaveau** [comment]
> Try:
> 
> ```
> zmodule g-plane/pnpm-shell-completion
> ```
> 
> I don't know Zim so I'm not sure whether it can work or not.

I get
```
pnpm _pnpm:17: aucun fichier ou dossier de ce type: /home/jean/.zim/modules/pnpm-shell-completion/pnpm-shell-completion
```
Which means, in french `no file or folder of the type...`

So I'm trying directly from a URL: `zmodule git@github.com:g-plane/pnpm-shell-completion.git` as explained here https://github.com/zimfw/zimfw?tab=readme-ov-file#zmodule

I then get `/home/jean/.zim/modules/pnpm-shell-completion/pnpm-shell-completion.plugin.zsh:91: command not found: compdef` which seems to be due to a conflict with zim autocomplete autoload

Placing it after `zmodule completion` in .zimrc fixed it but I still get the error telling that `.zim/modules/pnpm-shell-completion/pnpm-shell-completion` is missing when pressing tabtabtab to trigger autocomplete. Also, most proposed package.json scripts are missing


<details><summary>Here is my completion part of .zimrc</summary>
<p>

```sh
#
# Completion
#

# Additional completion definitions for Zsh.
zmodule zsh-users/zsh-completions --fpath src


# Enables and configures smart and extensive tab completion.
# completion must be sourced after all modules that add completion definitions.
zmodule completion

zmodule git@github.com:g-plane/pnpm-shell-completion.git

```
</p>
</details> 

As you can see, adding a completion script after `zmodule completion` is abnormal.


Do you know a `--path` or `--source` I should add to zmodule?

**Comment by g-plane** [comment]
Try this:

```
zmodule completion
zmodule git@github.com:g-plane/pnpm-shell-completion.git --on-pull './zplug.zsh'
```

**Comment by jclaveau** [comment]
> Try this:
> 
> ```
> zmodule completion
> zmodule git@github.com:g-plane/pnpm-shell-completion.git --on-pull './zplug.zsh'
> ```

It doesn't work so I manually changed dir to `/home/jean/.zim/modules/pnpm-shell-completion` and ran `./zplug.zsh`.

<details><summary>Details</summary>
<p>

```sh
❯❯❯❯ ./zplug.zsh                                                                                                                     ~/.z/m/pnpm-shell-completion main
Archive:  zipball.zip
replace pnpm-shell-completion? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: pnpm-shell-completion   
❯❯❯❯ pwd                                                                                                                             ~/.z/m/pnpm-shell-completion main
/home/jean/.zim/modules/pnpm-shell-completion
❯❯❯❯ ll                                                                                                                              ~/.z/m/pnpm-shell-completion main
total 2,3M
drwxrwxr-x 2 jean jean 4,0K juin  26 16:17 conf.d
drwxrwxr-x 2 jean jean 4,0K juin  26 16:17 src
-rw-rw-r-- 1 jean jean  16K juin  26 16:17 Cargo.lock
-rw-rw-r-- 1 jean jean  729 juin  26 16:17 Cargo.toml
-rw-rw-r-- 1 jean jean  336 juin  26 16:17 install.fish
-rwxrwxr-x 1 jean jean  340 juin  26 16:17 install.zsh
-r--r--r-- 1 jean jean 1,2K juin  26 16:17 install.zsh.zwc
-rw-rw-r-- 1 jean jean 1,1K juin  26 16:17 LICENSE
-rw-rw-r-- 1 jean jean 5,5K juin  26 16:17 pnpm.fish
-rwxr-xr-x 1 jean jean 2,2M mai    8 04:21 pnpm-shell-completion
-rw-rw-r-- 1 jean jean 4,8K juin  26 16:17 pnpm-shell-completion.plugin.zsh
-r--r--r-- 1 jean jean 8,6K juin  26 16:17 pnpm-shell-completion.plugin.zsh.zwc
-rw-rw-r-- 1 jean jean 8,4K juin  26 16:17 pnpm-shell-completion.ps1
-rw-rw-r-- 1 jean jean 4,0K juin  26 16:17 README.md
-rwxrwxr-x 1 jean jean  590 juin  26 16:17 zplug.zsh
-r--r--r-- 1 jean jean 2,0K juin  26 16:17 zplug.zsh.zwc

```

</p>
</details> 

Now it works but I don't know why the `--on-pull` didn't work

**Comment by jclaveau** [comment]
> What's the error message?

Erratum, it works with `--on-pull`, I just had to delete `/home/jean/.zim/modules/pnpm-shell-completion` first to retrigger the on pull event

Thank you very much for your fast answers and your work!

**Comment by g-plane** [comment]
I will update readme later.

**Comment by jclaveau** [comment]
Glad to here it, thanks again!
