### ISSUE TITLE
Suggestion: a branch for every architecture

### ISSUE THREAD

**Issue by habahabahaba** [g-plane/pnpm-shell-completion#27]
Hello and thank you for the plugin!
I wonder if it would be possible to create a separate branch for every architecture (apple-darwin, pc-windows etc.), so that the plugin could be installed on a specific machine without running the installation script?

**Comment by g-plane** [comment]
That will misuse Git branches and will be hard to maintain.

**Comment by habahabahaba** [comment]
Thank you for the quick response. I'll keep doing it by hand then.
