### ISSUE TITLE
Windows download triggering virus detection with Windows Security

### ISSUE THREAD

**Issue by eamodio** [g-plane/pnpm-shell-completion#29]
When I try to download the latest release for Windows (0.5.4), Edge blocks the download because it says it contains a virus. When I open Windows Security I see:
![image](https://github.com/user-attachments/assets/92f51fca-1417-4ae9-bd64-a75c7086f6eb)

FWIW, downloading `0.5.3` doesn't trigger any warnings

**Comment by g-plane** [comment]
This project is open source so you can build by yourself.

**Comment by eamodio** [comment]
Well aware thanks. But you might want to report it as a false positive (assuming it is - which from looking at the diff seems like it), as more users will likely be affected.
