### ISSUE TITLE
Add support for Debian

### ISSUE THREAD

**Issue by valerii15298** [g-plane/pnpm-shell-completion#6]
Latest version of Debian GNU/Linux 11 (bullseye) uses Glibc 2.31, but your package requires glibc >= 2.32.

Unfortunately, it is almost impossible to upgrade glibc on debian(it is easier to get new OS).

Are there plans for this library to support Debian at all?

**Comment by g-plane** [comment]
You can use the musl build.

**Comment by valerii15298** [comment]
Yep, but my point is also that updating glibc version and lot of other related stuff seems overhead for me just to get autocompletion, I would expect such library to be minimum dependant on other stuff...

**Comment by g-plane** [comment]
You don't need to update your glibc and just need to use the musl build of "pnpm-shell-completion".

**Comment by g-plane** [comment]
Closing. This has been already supported via musl build.
